MvcButton/Controllers/ButtonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcButton.Data;
using MvcButton.Models;

namespace MvcButton.Controllers
{
    public class ButtonsController : Controller
    {
        private readonly MvcButtonContext _context;

        public ButtonsController(MvcButtonContext context)
        {
            _context = context;
        }

        // GET: Buttons
        //public async Task<IActionResult> Index(string searchString)
        //{
        //    var buttons = from b in _context.Button
        //                 select b;

        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        buttons = buttons.Where(s => s.Brand.Contains(searchString));
        //    }

        //    return View(await buttons.ToListAsync());
        //}
        //updated the code

        // GET: Movies
        public async Task<IActionResult> Index(string buttonShape, string searchString)
        {
            // Use LINQ to get list of Shape.
            IQueryable<string> shapeQuery = from b in _context.Button
                                            orderby b.Shape
                                            select b.Shape;

            var buttons = from b in _context.Button
                         select b;

            if (!string.IsNullOrEmpty(searchString))
            {
                buttons = buttons.Where(s => s.Brand.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(buttonShape))
            {
                buttons = buttons.Where(x => x.Shape == buttonShape);
            }

            var buttonShapeVM = new ButtonShapeViewModel
            {
                Shape = new SelectList(await shapeQuery.Distinct().ToListAsync()),
                Buttons = await buttons.ToListAsync()
            };

            return View(buttonShapeVM);
        }
        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }
        // GET: Buttons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var button = await _context.Button
                .FirstOrDefaultAsync(m => m.Id == id);
            if (button == null)
            {
                return NotFound();
            }

            return View(button);
        }

        // GET: Buttons/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Buttons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Brand,Colour,Shape,Price,Rating")] Button button)
        {
            if (ModelState.IsValid)
            {
                _context.Add(button);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(button);
        }

        // GET: Buttons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var button = await _context.Button.FindAsync(id);
            if (button == null)
            {
                return NotFound();
            }
            return View(button);
        }

        // POST: Buttons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Brand,Colour,Shape,Price,Rating")] Button button)
        {
            if (id != button.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(button);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ButtonExists(button.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(button);
        }

        // GET: Buttons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var button = await _context.Button
                .FirstOrDefaultAsync(m => m.Id == id);
            if (button == null)
            {
                return NotFound();
            }

            return View(button);
        }

        // POST: Buttons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var button = await _context.Button.FindAsync(id);
            _context.Button.Remove(button);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ButtonExists(int id)
        {
            return _context.Button.Any(e => e.Id == id);
        }
    }
}

MvcButton/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Button App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            color:blueviolet;
            background-color: darksalmon;
        }
        h1{
            font-size:2em;
            font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Buttons" asp-action="Index">Button App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Button App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>